//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBook.Resource.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل المستخدم.
        /// </summary>
        public static string lbActiveUser {
            get {
                return ResourceManager.GetString("lbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string lbbtnChangePassword {
            get {
                return ResourceManager.GetString("lbbtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lbbtnDelete {
            get {
                return ResourceManager.GetString("lbbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbbtnEdit {
            get {
                return ResourceManager.GetString("lbbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbbtnSave {
            get {
                return ResourceManager.GetString("lbbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف مجموعة جديدة.
        /// </summary>
        public static string lbbtnSaveNewRole {
            get {
                return ResourceManager.GetString("lbbtnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string lbbtnSaveNewUser {
            get {
                return ResourceManager.GetString("lbbtnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعد كلمة المرور.
        /// </summary>
        public static string lbComparePassword {
            get {
                return ResourceManager.GetString("lbComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string lbEmailUser {
            get {
                return ResourceManager.GetString("lbEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحداث.
        /// </summary>
        public static string lbEvents {
            get {
                return ResourceManager.GetString("lbEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string lbImageUser {
            get {
                return ResourceManager.GetString("lbImageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الكتب.
        /// </summary>
        public static string lbManageBook {
            get {
                return ResourceManager.GetString("lbManageBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى او كلمة المرور غير صحيح.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغير كلمة المرور.
        /// </summary>
        public static string lbMsgNotSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير كلمة المرور بنجاح.
        /// </summary>
        public static string lbMsgSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string lbNameRole {
            get {
                return ResourceManager.GetString("lbNameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string lbNameUser {
            get {
                return ResourceManager.GetString("lbNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string lbNotSaved {
            get {
                return ResourceManager.GetString("lbNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة المستخدم.
        /// </summary>
        public static string lbNotSavedMsgRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ المستخدم.
        /// </summary>
        public static string lbNotSavedMsgUser {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ مجموعة المستخدم.
        /// </summary>
        public static string lbNotSavedMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التعديل.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تعديل مجموعة المستخدم.
        /// </summary>
        public static string lbNotUpdateMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة المستخدمين.
        /// </summary>
        public static string lbRoleUser {
            get {
                return ResourceManager.GetString("lbRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ مستخدم جديد بنجاح.
        /// </summary>
        public static string lbSaveMsgUser {
            get {
                return ResourceManager.GetString("lbSaveMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مجموعة المستخدم.
        /// </summary>
        public static string lbSelectUserRole {
            get {
                return ResourceManager.GetString("lbSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل مجموعة المستخدم بنجاح.
        /// </summary>
        public static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل المستخدم بنجاح.
        /// </summary>
        public static string lbUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين الحالين.
        /// </summary>
        public static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
    }
}
